# Generated by Django 4.2.4 on 2024-04-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0016_admininfo_mtn_api_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('User', 'User'), ('Agent', 'Agent'), ('Super Agent', 'Super Agent')], default='User', max_length=250),
        ),
    ]
